local formatters = {
  --'air',
  'asmfmt',
  --'ast_grep',
  --'beautysh',
  --'bibtex_tidy',
  'biome',
  'buf',
  'cljfmt',
  'djlint',
  'elm_format',
  --'erb_formatter',
  'fantomas',
  'gersemi',
  'gofumpt',
  'google_java_format',
  --'jupytext',
  --'ktfmt',
  --'kulala_fmt',
  --'nginx_config_formatter',
  'npm_groovy_lint',
  'ocamlformat',
  --'ormolu',
  'pg_format',
  'phpcbf',
  'prettier',
  'shellharden',
  'shfmt',
  'stylua',
  'terraform_fmt',
  --'vsg',
  --'wasm_opt',
  --'xmlformatter'
}

return formatters
