vim.opt.backup = false
vim.opt.clipboard = "unnamedplus"
vim.g.clipboard = {
  name = 'win32yank',
  copy = {
    ['+'] = 'win32yank.exe -i --crlf',
    ['*'] = 'win32yank.exe -i --crlf',
  },
  paste = {
    ['+'] = 'win32yank.exe -o --lf',
    ['*'] = 'win32yank.exe -o --lf',
  },
  cache_enabled = 0,
} 
vim.opt.cmdheight = 2
vim.opt.colorcolumn = "99999"
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.conceallevel = 0
vim.opt.fileencoding = "utf-8"
vim.opt.foldmethod = "manual"
vim.opt.foldexpr = ""
vim.opt.guifont = "monospace:h17"
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.mouse = "a"
vim.opt.pumheight = 10
vim.opt.showmode = false
vim.opt.showtabline = 2
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300
vim.opt.title = true
vim.opt.titlestring = "%<%F%=%1/&L - nvim" 
vim.opt.undodir = vim.fn.stdpath "cache" .. "/undo" 
vim.opt.undofile = true 
vim.opt.updatetime = 300
vim.opt.writebackup = false
vim.opt.expandtab = true 
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.cursorline = true 
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.numberwidth = 4 
vim.opt.signcolumn = "yes"
vim.opt.wrap = false
vim.opt.spell = false
vim.opt.spelllang = "en"
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
